# @package _global_

defaults:
  - emission: online
  - pre_process: cnext
  - path: local
  - hydra: custom
  - _self_

# --- Common args
datetime: ${now:%Y.%m.%d-%H.%M.%S}  # str
save_dir: "${hydra:sweep.dir}/${hydra:sweep.subdir}"
save_name: "${hydra:job.name}-${datetime}-custom_${hydra:runtime.choices.pre_process}"
seed: 42  # int | null
verbose: 1  # int (0 = WARNING, 1 = INFO, 2 = DEBUG)


# --- Prepare args
data:
  subsets: ["train", "test", "val"]  # list[str]
  download: true
  force: false

hdf_pattern: "{dataset}_{subset}_${hydra:runtime.choices.pre_process}.hdf"  # str
overwrite: false  # bool
batch_size: 32  # int
num_workers: 0  # int | "auto"
size_limit: null  # int | null